# 支持鼠标
set-option -g mouse on

# 前置按键设置
set-option -g prefix C-a

# 解决neovim esc延迟问题
set -sg escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

setw -g mode-keys vi # 开启vi风格后，支持vi的C-d、C-u、hjkl等快捷键

set -g base-index 1 # 设置窗口的起始下标为1
set -g pane-base-index 1 # 设置面板的起始下标为1

# 可切换回neovim界面 ThePrimeagen/harpoon提供
bind-key -r G run-shell "path-to-harpoon/harpoon/scripts/tmux/switch-back-to-nvim"

# https://github.com/projekt0n/github-nvim-theme
# Undercurl
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# 开启真彩色支持
set -g default-terminal "screen-256color"
set -sg terminal-overrides ",*:RGB"
